# Generated by Django 4.1.7 on 2023-03-18 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredientinrecipe_recipe_tag_shoppingcart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Формат HEX: #______', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Цвет в формате HEX'),
        ),
    ]
